package pt.uc.dei.fincos.controller.gui;

import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import pt.uc.dei.fincos.controller.ConnectionConfig;

/**
 *
 * @author Marcelo
 */
public class ConnectionsDialog extends ComponentDetail {

    private ArrayList<ConnectionConfig> connections;

    private Controller_GUI parent;

    private boolean dirty = false;

    /** Creates new form ConnectionsDialog */
    public ConnectionsDialog(Controller_GUI parent, ArrayList<ConnectionConfig> connections) {
        super(null);
        this.parent = parent;
        this.connections = new ArrayList<ConnectionConfig>();
        this.connections.addAll(connections);
        initComponents();
        fillGUI(connections);
        this.setModalityType(Dialog.DEFAULT_MODALITY_TYPE);
        addListeners();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    private void fillGUI(List<ConnectionConfig> connections) {
        DefaultTableModel model = (DefaultTableModel) this.connectionsTable.getModel();
        for (ConnectionConfig c : connections) {
            model.addRow(new Object[] {c.alias, c.type == ConnectionConfig.CEP_ADAPTER ? "CEP Adapter" : "JMS"});
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        connectionsTable = new javax.swing.JTable();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        connLbl = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Connection Configuration");

        connectionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alias", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(connectionsTable);
        connectionsTable.setAutoCreateRowSorter(true);

        addBtn.setText("Add...");
        addBtn.setPreferredSize(new java.awt.Dimension(70, 23));

        deleteBtn.setText("Delete");
        deleteBtn.setPreferredSize(new java.awt.Dimension(70, 23));

        connLbl.setText("Available Connections:");

        okBtn.setIcon(new javax.swing.ImageIcon("imgs/ok.png")); // NOI18N
        okBtn.setText("OK");
        okBtn.setPreferredSize(new java.awt.Dimension(90, 30));

        cancelBtn.setIcon(new javax.swing.ImageIcon("imgs/cancel.png"));
        cancelBtn.setText("Cancel");
        cancelBtn.setPreferredSize(new java.awt.Dimension(95, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(connLbl)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(connLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();

        connectionsTable.getColumnModel().getColumn(0).setPreferredWidth(150);
        connectionsTable.getColumnModel().getColumn(1).setPreferredWidth(50);
    }// </editor-fold>

    private void addListeners() {
        cancelBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (dirty) {
                   if (JOptionPane.showConfirmDialog(null, "Discard changes?", "", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                      dispose();
                   }
                } else {
                    dispose();
                }
            }

        });

        okBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (dirty) {
                    parent.setConnections(connections);
                    try {
                        parent.saveConnections();
                    } catch (Exception e1) {
                        JOptionPane.showMessageDialog(null, "Error while saving connections file. Message: "
                                + e1.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
                dispose();
            }
        });

        addBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ConnectionDetail connDetail = openConnectionDetail(null);
            }

        });

        deleteBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                DefaultTableModel model = (DefaultTableModel) connectionsTable.getModel();
                int selected = connectionsTable.convertRowIndexToModel(connectionsTable.getSelectedRow());
                if (selected != -1) {
                    int confirmDelete  = JOptionPane.showConfirmDialog(null, "Do you want to permanently remove this connection from the repository? "
                            + "(WARN: The connection will be unavailable for this and other test setups)", "Confirm deletion", JOptionPane.YES_NO_OPTION);
                    if (confirmDelete == JOptionPane.YES_OPTION) {
                        connections.remove(selected);
                        model.removeRow(selected);
                        dirty = true;
                    }
                }
            }
        });

        connectionsTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    JTable source = (JTable) e.getSource();
                    if (source.isEnabled()) {
                        int selected = connectionsTable.convertRowIndexToModel(connectionsTable.getSelectedRow());
                        if (selected > -1) {
                            openConnectionDetail(connections.get(selected));
                        }
                    }
                }
            }
        });
    }

    /**
     * Creates a form for configuring a connection.
     *
     * @param connCfg   Workload phase configuration properties, when in UPDATE mode,
     *                  or <tt>null</tt>, in INSERTION mode.
     * @return          a reference to the just created form
     */
    protected ConnectionDetail openConnectionDetail(ConnectionConfig connCfg) {
        return new ConnectionDetail(this, connCfg);
    }

    /**
     * Checks unique constraint for a given connection name.
     *
     * @param alias     connection alias
     * @return          <tt>true</tt> if there is no other connection in the set with the alias
     *                  passed as argument, <tt>false</tt> otherwise.
     */
    protected boolean isUnique(String alias) {
        for (ConnectionConfig c : this.connections) {
            if (c.alias.equals(alias)) {
                return false;
            }
        }
        return true;
    }

    /**
     * Add a new connection to the list of available connections.
     *
     * @param connCfg   the new connection
     */
    protected void addConnection(ConnectionConfig connCfg) {
        this.connections.add(connCfg);
        ((DefaultTableModel)this.connectionsTable.getModel()).addRow(
                new Object[] {connCfg.alias, connCfg.type == ConnectionConfig.CEP_ADAPTER ? "CEP Adapter" : "JMS"});
        dirty = true;
    }

    /**
     * Updates an existing connection.
     *
     * @param oldCfg    old configuration
     * @param newCfg    new configuration
     */
    protected void updateConnection(ConnectionConfig oldCfg, ConnectionConfig newCfg) {
        int index = this.connections.indexOf(oldCfg);
        this.connections.remove(index);
        this.connections.add(index, newCfg);
        ((DefaultTableModel) connectionsTable.getModel()).removeRow(index);
        ((DefaultTableModel) connectionsTable.getModel()).insertRow(index,
                new Object[] {newCfg.alias, newCfg.type == ConnectionConfig.CEP_ADAPTER ? "CEP Adapter" : "JMS"});
        dirty = true;
    }

    // Variables declaration - do not modify
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel connLbl;
    private javax.swing.JTable connectionsTable;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okBtn;
    // End of variables declaration

}
