package pt.uc.dei.fincos.adapters;

import pt.uc.dei.fincos.basic.CSV_Event;
import pt.uc.dei.fincos.basic.Event;

/**
 * Interface to send events to a CEP engine or a JMS Provider.
 *
 * @author Marcelo R.N. Mendes
 */
public interface InputAdapter {
    /**
     *
     *
     * Converts and sends events generated by FINCoS to the target system.
     * Events are strongly typed.
     *
     *
     * @param e             the event to be converted and sent
     * @throws Exception    if an error occurs during event submission
     */
    void send(Event e) throws Exception;

    /**
    *
    * Converts and sends events read from data files to the target system.
    * Events attributes are not typed (all Strings).
    *
    * (IMPLEMENTATIONS OF THIS METHOD MUST BE THREAD-SAFE!)
    *
    * @param e             the event to be converted and sent
    * @throws Exception    if an error occurs during event submission
    */
    void send(CSV_Event event);
}
